import { Metadata } from "next";
import "./globals.css";
import Navigation from "../components/Navigation";
import { CartProvider } from "../context/CartContext";
import { SearchProvider } from "../context/SearchContext"; // Import the SearchContext

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body>
        <CartProvider>
          <SearchProvider>
            <Navigation />
            {children}
          </SearchProvider>
        </CartProvider>
      </body>
    </html>
  );
}
